name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
    - uses: actions/checkout@v4.2.2
      with:
        submodules: true
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
    - name: Use Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: '24'
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile
    - name: Build
      run: pnpm build
    - name: Migrate
      run: pnpm migrate
    - name: Test
      run: pnpm test
